### ISSUE TITLE
Unable to pull docker image cezerin2/cezerin2

### ISSUE THREAD

**Issue by kdpisda** [Cezerin2/Server#42]
I am unable to pull docker image it says 
`ERROR: pull access denied for cezerin2/cezerin2, repository does not exist or may require 'docker login'`

I have logged in with the docker too.

My docker-compose file
```
version: '3'

services:
  app:
    image: cezerin2/cezerin2
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shop
      - DB_USER=store
      - DB_PASS=Qwertyuiop~
    ports:
      - 4000:80
    volumes:
      - /var/www/store:/var/www/cezerin
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    ports:
      - 27017
    volumes:
      - /var/www/store-db:/data/db
    restart: always
```
